### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by Samsonroyal** [FotieMConstant/gitsocial#3]
The [README.md](https://github.com/FotieMConstant/gitsocial)  has a couple of errors caused by mishaps in the grammar and or syntax of the English used.
 
In the
 <b>“why did you make this”</b>
section I believe the heading/title itself should be something like 
<b>“Why we made this?”</b>
if the gitsocial repo is to be contributed to by more than one dev; the “we” is more appropriate to use

The other issue is about the re-arrangement of some sentences under this previous section I mentioned to make them correct grammatically. 
 
 That’s what I would love us to start with working upon to make gitsocial more <b>dev-friendly</b>😂

Regards,
<i>Psalmson ❤️</i>

**Comment by FotieMConstant** [comment]
This makes a lot of sense. Please could you solve that in a PR? Thanks

**Comment by Samsonroyal** [comment]
Now that I’ve gotten your confirmation let me proceed to do just that.

**Comment by FotieMConstant** [comment]
Hi, @Samsonroyal I guess this issue can be closed!

**Comment by Samsonroyal** [comment]
Yes, and with gratitude 🔥😂😂
